"use client";
import React from "react";
import { Shield, FileText, Music2 } from "lucide-react";
import PageShell from "../components/PageShell";

// Privacy & Policy page.
export default function PrivacyPolicyPage() {
  return (
    <PageShell>
      <div className="max-w-4xl w-full space-y-8">
        <header className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 bg-[var(--md-surface-2)] border border-[var(--md-outline)] px-4 py-2 rounded-full backdrop-blur-xl">
            <Shield className="w-4 h-4 text-[var(--md-secondary)]" />
            <span className="text-xs font-semibold uppercase tracking-[0.3em] text-[var(--md-text-muted)]">
              Privacy & Policy
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-semibold">EditorsChoice Privacy & Policy</h1>
          <p className="text-[var(--md-text-muted)] text-sm sm:text-base">
            This page explains how EditorsChoice works and how we handle data. Our goal is clarity for creators,
            monetization partners, and platform reviewers.
          </p>
        </header>

        <section className="bg-[var(--md-surface-2)] border border-[var(--md-outline)] rounded-[24px] p-6 sm:p-8 space-y-6 backdrop-blur-xl shadow-lg">
          <div className="flex items-start gap-3">
            <Music2 className="w-5 h-5 text-[var(--md-primary)] mt-1" />
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Purpose of the Project</h2>
              <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
                EditorsChoice is a recommendation tool that provides song ideas for video editors and content creators.
                We do not distribute or host full songs, and we do not claim ownership over any music.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-[var(--md-primary)] mt-1" />
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Data We Collect</h2>
              <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
                We do not collect personal information such as your name, email, phone number, or payment details.
                Inputs you provide (category, feeling, language, and tags) are used only to generate recommendations and
                are not stored as personal profiles.
              </p>
            </div>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">How We Use Data</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              Your inputs are processed to produce song suggestions. We use this information only to deliver the
              results you request. We do not sell, rent, or share user data with advertisers.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Cookies & Tracking</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              EditorsChoice does not set tracking cookies for advertising. If analytics are enabled in the future, they
              will be limited to anonymous usage metrics to improve the product.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">AI-Generated Suggestions</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              Recommendations are generated by AI and are provided for inspiration only. Please verify music licensing
              requirements with the original rights holders before using any song in commercial content.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Copyright & Monetization</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              We do not provide downloads of copyrighted audio and do not encourage infringement. Users are responsible
              for obtaining proper licenses for monetized content. EditorsChoice is designed to comply with platform
              guidelines by offering ideas, not distributing media.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Security</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              We take reasonable measures to protect the service from unauthorized access. Since we do not collect
              personal data, the risk of sensitive data exposure is minimized.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Policy Updates</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              We may update this policy to reflect product changes. Updates will appear on this page with a revised
              effective date.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Contact</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              For questions about this policy, please contact the site owner or administrator.
            </p>
          </div>
        </section>

        <p className="text-center text-[11px] sm:text-xs text-[var(--md-text-muted)]">
          Effective Date: March 9, 2026
        </p>
      </div>
    </PageShell>
  );
}
