"use client";
import React from "react";
import { Shield, FileText, Music2 } from "lucide-react";
import PageShell from "../components/PageShell";

// Privacy & Policy page.
export default function PrivacyPolicyPage() {
  return (
    <PageShell>
      <div className="max-w-4xl w-full space-y-8">
        <header className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 bg-[var(--md-surface-2)] border border-[var(--md-outline)] px-4 py-2 rounded-full backdrop-blur-xl">
            <Shield className="w-4 h-4 text-[var(--md-secondary)]" />
            <span className="text-xs font-semibold uppercase tracking-[0.3em] text-[var(--md-text-muted)]">
              Privacy & Policy
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-semibold">EditorsChoice Privacy & Policy</h1>
          <p className="text-[var(--md-text-muted)] text-sm sm:text-base">
            This page explains how EditorsChoice works and how we handle data. Our goal is clarity for creators,
            monetization partners, and platform reviewers.
          </p>
        </header>

        <section className="bg-[var(--md-surface-2)] border border-[var(--md-outline)] rounded-[24px] p-6 sm:p-8 space-y-6 backdrop-blur-xl shadow-lg">
          <div className="flex items-start gap-3">
            <Music2 className="w-5 h-5 text-[var(--md-primary)] mt-1" />
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Purpose of the Project</h2>
              <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
                EditorsChoice is a recommendation tool that provides song ideas for video editors and content creators.
                We do not distribute or host full songs, and we do not claim ownership over any music.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-[var(--md-primary)] mt-1" />
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Data We Collect</h2>
              <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
                We collect limited information that is necessary to run the service. This can include the song-search
                inputs you submit, basic technical data related to your visit, and the contact details you choose to
                send through the feedback form such as your name, email address, subject, and message.
              </p>
            </div>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">How We Use Data</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              Search inputs are processed to generate recommendations and improve reliability. Contact form details are
              used only to review messages and reply when needed. We do not sell personal information or build
              advertising profiles from your song-search requests.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Cookies & Tracking</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              EditorsChoice uses analytics tools that may set cookies or similar technologies to measure traffic,
              understand usage patterns, and improve the site. We do not currently use AdSense on this website, and we
              do not use contact form submissions to serve personalized ads.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">AI-Generated Suggestions</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              Recommendations are generated by AI and are provided for inspiration only. Please verify music licensing
              requirements with the original rights holders before using any song in commercial content.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Copyright & Monetization</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              We do not provide downloads of copyrighted audio and do not encourage infringement. Users are responsible
              for obtaining proper licenses for monetized content. EditorsChoice is designed to comply with platform
              guidelines by offering ideas, not distributing media.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Security</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              We take reasonable measures to protect the service from unauthorized access. No system is guaranteed to be
              perfectly secure, but we limit data collection and use standard service protections where practical.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Policy Updates</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              We may update this policy to reflect product changes. Updates will appear on this page with a revised
              effective date.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Contact</h2>
            <p className="text-[var(--md-text-muted)] text-sm leading-relaxed">
              For questions about this policy, please use the contact page or email{" "}
              <a
                href="mailto:kjyotish124@gmail.com"
                className="text-[var(--md-primary)] underline underline-offset-4"
              >
                kjyotish124@gmail.com
              </a>
              .
            </p>
          </div>
        </section>

        <p className="text-center text-[11px] sm:text-xs text-[var(--md-text-muted)]">
          Effective Date: March 25, 2026
        </p>
      </div>
    </PageShell>
  );
}

